### PR TITLE
Pr Create a built docker image

### PR DESCRIPTION
**Pull request by SergioGlorias**
I think we could provide a picture for those who just want to self-host and not have to weigh the build

my example: https://github.com/SergioGlorias/fide/pkgs/container/fide

### CODE REVIEW

**Comment by lenguyenthanh** [comment]
Thanks! this is a great idea. And We already can build image with `sbt backend/publishLocal`: https://github.com/lenguyenthanh/fide/blob/main/build.sbt#L94-L97. 

I'm not sure it works right now, but it's probably better optimize than our custom dockerfile.

**Comment by lenguyenthanh** [comment]
I fixed baseimage for built docker image, but still couldn't make it work with `docker-compose.example.yml`. We probably need a better ways to setup environment variables.

**Comment by SergioGlorias** [comment]
> I fixed baseimage for built docker image, but still couldn't make it work with `docker-compose.example.yml`. We probably need a better ways to setup environment variables.

From my tests, the code continues to only read the .env file

**Comment by SergioGlorias** [comment]
docker compose reads `.env` but the api doesn't

**Comment by lenguyenthanh** [comment]
superseded by #56, thanks @SergioGlorias for the idea and your work!

**Pull request closed without merging**
